apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Kyverno v1.13.4 official install manifest
- https://github.com/kyverno/kyverno/releases/download/v1.13.4/install.yaml
# Custom policies
- inject-oauth-proxy.yaml
