apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# External Secrets Operator
- eso/namespace.yaml
- eso/subscription.yaml
- eso/operatorconfig.yaml
- eso/serviceaccount.yaml
- eso/cluster-store.yaml
