apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# OpenShift GitOps Operator (ArgoCD)
- openshift-gitops

# External Secrets Operator
- external-secrets-operator

# Kyverno Policy Engine
- kyverno
