apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# AWS Load Balancer Operator
- aws-load-balancer-operator/namespace.yaml
- aws-load-balancer-operator/operatorgroup.yaml
- aws-load-balancer-operator/subscription.yaml
- aws-load-balancer-operator/controller.yaml

# External Secrets Operator
- eso/namespace.yaml
- eso/subscription.yaml
- eso/operatorconfig.yaml
- eso/serviceaccount.yaml
- eso/cluster-store.yaml
