apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-app
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: nginx-tls
spec:
  selector:
    app: nginx
  ports:
  - name: proxy
    port: 8443
    targetPort: 8443
